-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axis_controller\AxisController_dut.vhd
-- Created: 2021-02-09 13:59:41
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: AxisController_dut
-- Source Path: AxisController/AxisController_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY AxisController_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        Enable                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Value                             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        m_axis_tready                     :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        m_axis_tdata                      :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
        m_axis_tvalid                     :   OUT   std_logic  -- ufix1
        );
END AxisController_dut;


ARCHITECTURE rtl OF AxisController_dut IS

  -- Component Declarations
  COMPONENT AxisController_src_AXI_Stream_Controller
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          Enable                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Value                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          m_axis_tready                   :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          m_axis_tdata                    :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
          m_axis_tvalid                   :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : AxisController_src_AXI_Stream_Controller
    USE ENTITY work.AxisController_src_AXI_Stream_Controller(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL m_axis_tready_sig                : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL m_axis_tdata_sig                 : std_logic_vector(127 DOWNTO 0);  -- ufix128
  SIGNAL m_axis_tvalid_sig                : std_logic;  -- ufix1

BEGIN
  u_AxisController_src_AXI_Stream_Controller : AxisController_src_AXI_Stream_Controller
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              Enable => Enable,  -- ufix32
              Value => Value,  -- ufix32
              m_axis_tready => m_axis_tready_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              m_axis_tdata => m_axis_tdata_sig,  -- ufix128
              m_axis_tvalid => m_axis_tvalid_sig  -- ufix1
              );

  m_axis_tready_sig <= m_axis_tready;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  m_axis_tdata <= m_axis_tdata_sig;

  m_axis_tvalid <= m_axis_tvalid_sig;

END rtl;

