-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axis_packet_generator\AxisPacketGenerator_axi4_stream_imag_master.vhd
-- Created: 2021-02-09 12:52:42
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: AxisPacketGenerator_axi4_stream_imag_master
-- Source Path: AxisPacketGenerator/AxisPacketGenerator_axi4_stream_imag_master
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY AxisPacketGenerator_axi4_stream_imag_master IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXI4_Stream_Imag_Master_TREADY    :   IN    std_logic;  -- ufix1
        user_data                         :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
        user_valid                        :   IN    std_logic;  -- ufix1
        user_TLAST                        :   IN    std_logic;  -- ufix1
        AXI4_Stream_Imag_Master_TDATA     :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
        AXI4_Stream_Imag_Master_TVALID    :   OUT   std_logic;  -- ufix1
        AXI4_Stream_Imag_Master_TLAST     :   OUT   std_logic;  -- ufix1
        user_ready                        :   OUT   std_logic  -- ufix1
        );
END AxisPacketGenerator_axi4_stream_imag_master;


ARCHITECTURE rtl OF AxisPacketGenerator_axi4_stream_imag_master IS

  -- Component Declarations
  COMPONENT AxisPacketGenerator_fifo_data_OUT_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
          Empty                           :   OUT   std_logic;  -- ufix1
          AFull                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT AxisPacketGenerator_fifo_TLAST_OUT_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic;  -- ufix1
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : AxisPacketGenerator_fifo_data_OUT_block
    USE ENTITY work.AxisPacketGenerator_fifo_data_OUT_block(rtl);

  FOR ALL : AxisPacketGenerator_fifo_TLAST_OUT_block
    USE ENTITY work.AxisPacketGenerator_fifo_TLAST_OUT_block(rtl);

  -- Signals
  SIGNAL AXI4_Stream_Imag_Master_TDATA_tmp : std_logic_vector(127 DOWNTO 0);  -- ufix128
  SIGNAL fifo_empty_data                  : std_logic;  -- ufix1
  SIGNAL fifo_afull_data                  : std_logic;  -- ufix1
  SIGNAL internal_ready                   : std_logic;  -- ufix1

BEGIN
  u_AxisPacketGenerator_fifo_data_OUT_inst : AxisPacketGenerator_fifo_data_OUT_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => user_data,  -- ufix128
              Push => user_valid,  -- ufix1
              Pop => AXI4_Stream_Imag_Master_TREADY,  -- ufix1
              Out_rsvd => AXI4_Stream_Imag_Master_TDATA_tmp,  -- ufix128
              Empty => fifo_empty_data,  -- ufix1
              AFull => fifo_afull_data  -- ufix1
              );

  u_AxisPacketGenerator_fifo_TLAST_OUT_inst : AxisPacketGenerator_fifo_TLAST_OUT_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => user_TLAST,  -- ufix1
              Push => user_valid,  -- ufix1
              Pop => AXI4_Stream_Imag_Master_TREADY,  -- ufix1
              Out_rsvd => AXI4_Stream_Imag_Master_TLAST  -- ufix1
              );

  AXI4_Stream_Imag_Master_TVALID <=  NOT fifo_empty_data;

  internal_ready <=  NOT fifo_afull_data;

  user_ready <= internal_ready;

  AXI4_Stream_Imag_Master_TDATA <= AXI4_Stream_Imag_Master_TDATA_tmp;

END rtl;

