-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axis_packet_generator\AxisPacketGenerator_src_SR_Latch.vhd
-- Created: 2021-02-09 12:52:35
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: AxisPacketGenerator_src_SR_Latch
-- Source Path: axis_packet_generator/AXI-Stream Packet Generator/Packet Inspector Real/SR Latch
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY AxisPacketGenerator_src_SR_Latch IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        S                                 :   IN    std_logic;
        R                                 :   IN    std_logic;
        Q                                 :   OUT   std_logic
        );
END AxisPacketGenerator_src_SR_Latch;


ARCHITECTURE rtl OF AxisPacketGenerator_src_SR_Latch IS

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Multiport_Switch_out1            : std_logic;
  SIGNAL Unit_Delay_Resettable_Synchronous_out1 : std_logic;

BEGIN
  Constant_out1 <= '1';

  Unit_Delay_Resettable_Synchronous_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Resettable_Synchronous_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF R = '1' THEN
          Unit_Delay_Resettable_Synchronous_out1 <= '0';
        ELSE 
          Unit_Delay_Resettable_Synchronous_out1 <= Multiport_Switch_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Resettable_Synchronous_process;


  
  Multiport_Switch_out1 <= Unit_Delay_Resettable_Synchronous_out1 WHEN S = '0' ELSE
      Constant_out1;

  Q <= Multiport_Switch_out1;

END rtl;

