-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axis_packet_generator\AxisPacketGenerator_src_AXI_Stream_Packet_Generator.vhd
-- Created: 2021-02-09 12:52:35
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 3.90625e-09
-- Target subsystem base rate: 3.90625e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        3.90625e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- m_axis_re_tdata               ce_out        3.90625e-09
-- m_axis_re_tvalid              ce_out        3.90625e-09
-- m_axis_re_tlast               ce_out        3.90625e-09
-- m_axis_im_tdata               ce_out        3.90625e-09
-- m_axis_im_tvalid              ce_out        3.90625e-09
-- m_axis_im_tlast               ce_out        3.90625e-09
-- s_axis_re_tready              ce_out        3.90625e-09
-- s_axis_im_tready              ce_out        3.90625e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: AxisPacketGenerator_src_AXI_Stream_Packet_Generator
-- Source Path: axis_packet_generator/AXI-Stream Packet Generator
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY AxisPacketGenerator_src_AXI_Stream_Packet_Generator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        packet_size                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        transfer                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        s_axis_re_tdata                   :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
        s_axis_re_tvalid                  :   IN    std_logic;
        s_axis_im_tdata                   :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
        s_axis_im_tvalid                  :   IN    std_logic;
        m_axis_re_tready                  :   IN    std_logic;
        m_axis_im_tready                  :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        m_axis_re_tdata                   :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
        m_axis_re_tvalid                  :   OUT   std_logic;
        m_axis_re_tlast                   :   OUT   std_logic;
        m_axis_im_tdata                   :   OUT   std_logic_vector(127 DOWNTO 0);  -- ufix128
        m_axis_im_tvalid                  :   OUT   std_logic;
        m_axis_im_tlast                   :   OUT   std_logic;
        s_axis_re_tready                  :   OUT   std_logic;
        s_axis_im_tready                  :   OUT   std_logic
        );
END AxisPacketGenerator_src_AXI_Stream_Packet_Generator;


ARCHITECTURE rtl OF AxisPacketGenerator_src_AXI_Stream_Packet_Generator IS

  -- Component Declarations
  COMPONENT AxisPacketGenerator_src_Packet_Generator_Real
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Packet_Size                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Valid_In                        :   IN    std_logic;
          Data_In                         :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          End_Out                         :   OUT   std_logic;
          Start_Out                       :   OUT   std_logic;
          Valid_Out                       :   OUT   std_logic;
          Data_Out                        :   OUT   std_logic_vector(127 DOWNTO 0)  -- ufix128
          );
  END COMPONENT;

  COMPONENT AxisPacketGenerator_src_Packet_Inspector_Real
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          transfer                        :   IN    std_logic;  -- ufix1
          End_In                          :   IN    std_logic;
          Start_In                        :   IN    std_logic;
          Valid_In                        :   IN    std_logic;
          Data_In                         :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          End_Out                         :   OUT   std_logic;
          Valid_Out                       :   OUT   std_logic;
          Data_Out                        :   OUT   std_logic_vector(127 DOWNTO 0)  -- ufix128
          );
  END COMPONENT;

  COMPONENT AxisPacketGenerator_src_Packet_Generator_Imag
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Packet_Size                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Valid_In                        :   IN    std_logic;
          Data_In                         :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          End_Out                         :   OUT   std_logic;
          Start_Out                       :   OUT   std_logic;
          Valid_Out                       :   OUT   std_logic;
          Data_Out                        :   OUT   std_logic_vector(127 DOWNTO 0)  -- ufix128
          );
  END COMPONENT;

  COMPONENT AxisPacketGenerator_src_Packet_Inspector_Real1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          transfer                        :   IN    std_logic;  -- ufix1
          End_In                          :   IN    std_logic;
          Start_In                        :   IN    std_logic;
          Valid_In                        :   IN    std_logic;
          Data_In                         :   IN    std_logic_vector(127 DOWNTO 0);  -- ufix128
          End_Out                         :   OUT   std_logic;
          Valid_Out                       :   OUT   std_logic;
          Data_Out                        :   OUT   std_logic_vector(127 DOWNTO 0)  -- ufix128
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : AxisPacketGenerator_src_Packet_Generator_Real
    USE ENTITY work.AxisPacketGenerator_src_Packet_Generator_Real(rtl);

  FOR ALL : AxisPacketGenerator_src_Packet_Inspector_Real
    USE ENTITY work.AxisPacketGenerator_src_Packet_Inspector_Real(rtl);

  FOR ALL : AxisPacketGenerator_src_Packet_Generator_Imag
    USE ENTITY work.AxisPacketGenerator_src_Packet_Generator_Imag(rtl);

  FOR ALL : AxisPacketGenerator_src_Packet_Inspector_Real1
    USE ENTITY work.AxisPacketGenerator_src_Packet_Inspector_Real1(rtl);

  -- Signals
  SIGNAL transfer_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bit_Slice_out1                   : std_logic;  -- ufix1
  SIGNAL Packet_Generator_Real_out1       : std_logic;
  SIGNAL Packet_Generator_Real_out2       : std_logic;
  SIGNAL Packet_Generator_Real_out3       : std_logic;
  SIGNAL y                                : std_logic_vector(127 DOWNTO 0);  -- ufix128
  SIGNAL Packet_Inspector_Real_out1       : std_logic;
  SIGNAL Packet_Inspector_Real_out2       : std_logic;
  SIGNAL Packet_Inspector_Real_out3       : std_logic_vector(127 DOWNTO 0);  -- ufix128
  SIGNAL Packet_Generator_Imag_out1       : std_logic;
  SIGNAL Packet_Generator_Imag_out2       : std_logic;
  SIGNAL Packet_Generator_Imag_out3       : std_logic;
  SIGNAL y_1                              : std_logic_vector(127 DOWNTO 0);  -- ufix128
  SIGNAL Packet_Inspector_Real1_out1      : std_logic;
  SIGNAL Packet_Inspector_Real1_out2      : std_logic;
  SIGNAL Packet_Inspector_Real1_out3      : std_logic_vector(127 DOWNTO 0);  -- ufix128
  SIGNAL Constant_out1                    : std_logic;

BEGIN
  u_Packet_Generator_Real : AxisPacketGenerator_src_Packet_Generator_Real
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Packet_Size => packet_size,  -- uint32
              Valid_In => s_axis_re_tvalid,
              Data_In => s_axis_re_tdata,  -- ufix128
              End_Out => Packet_Generator_Real_out1,
              Start_Out => Packet_Generator_Real_out2,
              Valid_Out => Packet_Generator_Real_out3,
              Data_Out => y  -- ufix128
              );

  u_Packet_Inspector_Real : AxisPacketGenerator_src_Packet_Inspector_Real
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              transfer => Bit_Slice_out1,  -- ufix1
              End_In => Packet_Generator_Real_out1,
              Start_In => Packet_Generator_Real_out2,
              Valid_In => Packet_Generator_Real_out3,
              Data_In => y,  -- ufix128
              End_Out => Packet_Inspector_Real_out1,
              Valid_Out => Packet_Inspector_Real_out2,
              Data_Out => Packet_Inspector_Real_out3  -- ufix128
              );

  u_Packet_Generator_Imag : AxisPacketGenerator_src_Packet_Generator_Imag
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Packet_Size => packet_size,  -- uint32
              Valid_In => s_axis_im_tvalid,
              Data_In => s_axis_im_tdata,  -- ufix128
              End_Out => Packet_Generator_Imag_out1,
              Start_Out => Packet_Generator_Imag_out2,
              Valid_Out => Packet_Generator_Imag_out3,
              Data_Out => y_1  -- ufix128
              );

  u_Packet_Inspector_Real1 : AxisPacketGenerator_src_Packet_Inspector_Real1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              transfer => Bit_Slice_out1,  -- ufix1
              End_In => Packet_Generator_Imag_out1,
              Start_In => Packet_Generator_Imag_out2,
              Valid_In => Packet_Generator_Imag_out3,
              Data_In => y_1,  -- ufix128
              End_Out => Packet_Inspector_Real1_out1,
              Valid_Out => Packet_Inspector_Real1_out2,
              Data_Out => Packet_Inspector_Real1_out3  -- ufix128
              );

  transfer_unsigned <= unsigned(transfer);

  Bit_Slice_out1 <= transfer_unsigned(0);

  Constant_out1 <= '1';

  ce_out <= clk_enable;

  m_axis_re_tdata <= Packet_Inspector_Real_out3;

  m_axis_re_tvalid <= Packet_Inspector_Real_out2;

  m_axis_re_tlast <= Packet_Inspector_Real_out1;

  m_axis_im_tdata <= Packet_Inspector_Real1_out3;

  m_axis_im_tvalid <= Packet_Inspector_Real1_out2;

  m_axis_im_tlast <= Packet_Inspector_Real1_out1;

  s_axis_re_tready <= Constant_out1;

  s_axis_im_tready <= Constant_out1;

END rtl;

